language: node_js
sudo: required
services: mongodb
matrix:
  include:
    - node_js: "stable"
      before_script:
        - npm install -g mocha nyc coveralls mocha-lcov-reporter --save-dev
      after_success:
        - npm run coverage
